version: "2"
run:
  tests: true
linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - revive
    - unparam
    - gocyclo
    - dupl
  settings:
    gocyclo:
      min-complexity: 15
    revive:
      severity: warning
      rules:
        - name: exported
          severity: error
  exclusions:
    generated: lax
    rules:
      - path: (.+)\.go$
        text: ST1000
      - path: (.+)\.go$
        text: U1000
      - path: (.+)\.go$
        text: QF1002
    paths:
      - third_party$
      - builtin$
      - examples$
    presets:
      - comments
issues:
  max-issues-per-linter: 50
  max-same-issues: 10

formatters:
  enable:
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
