-- +goose Up
-- +goose StatementBegin
CREATE TABLE withdrawals (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_name TEXT REFERENCES users(name) NOT NULL,
        order_id BIGINT NOT NULL UNIQUE,
        sum NUMERIC NOT NULL DEFAULT 0,
        processed_at TIMESTAMP NOT NULL DEFAULT now()
)
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS withdrawals;
-- +goose StatementEnd
